# Generated by Django 4.2.2 on 2024-07-08 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Введите ФИО",
                        max_length=150,
                        null=True,
                        verbose_name="ФИО",
                    ),
                ),
                (
                    "comment",
                    models.TextField(max_length=350, verbose_name="Комментарий"),
                ),
            ],
            options={
                "verbose_name": "клиент",
                "verbose_name_plural": "клиенты",
            },
        ),
        migrations.CreateModel(
            name="MailingMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        help_text="Введите тему письма",
                        max_length=30,
                        verbose_name="Тема письма",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        help_text="Введите сообщение для рассылки",
                        max_length=350,
                        verbose_name="Тело письма",
                    ),
                ),
            ],
            options={
                "verbose_name": "рассылка (текст)",
                "verbose_name_plural": "рассылки (текст)",
            },
        ),
        migrations.CreateModel(
            name="MailingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_sent_datetime",
                    models.DateTimeField(
                        help_text="Укажите дату и время первой отправки рассылки",
                        verbose_name="дата и время первой отправки рассылки",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        help_text="Укажите периодичность: раз в день, раз в неделю, раз в месяц",
                        max_length=150,
                        verbose_name="периодичность",
                    ),
                ),
                ("clients", models.ManyToManyField(to="mailing.client")),
                (
                    "mailing_message",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mailing.mailingmessage",
                        verbose_name="Текст рассылки",
                    ),
                ),
            ],
            options={
                "verbose_name": "рассылка (настройки)",
                "verbose_name_plural": "рассылки (настройки)",
            },
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_try_sent_datetime",
                    models.DateTimeField(
                        verbose_name="дата и время последней попытки рассылки"
                    ),
                ),
                ("status", models.BooleanField(null=True, verbose_name="Статус")),
                (
                    "server_reply",
                    models.TextField(
                        blank=True, null=True, verbose_name="ответ почтового сервера"
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.mailingsettings",
                        verbose_name="Настройка рассылки",
                    ),
                ),
            ],
            options={
                "verbose_name": "попытка рассылки",
                "verbose_name_plural": "попытки рассылок",
            },
        ),
    ]
