# Generated by Django 4.2.2 on 2024-07-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_mailingmessage_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingsettings",
            name="first_sent_datetime",
            field=models.CharField(
                help_text="Укажите дату и время первой отправки рассылки",
                verbose_name="дата и время первой отправки рассылки",
            ),
        ),
    ]
