# Generated by Django 4.2.2 on 2024-07-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_alter_mailingsettings_first_sent_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingsettings",
            name="clients",
            field=models.ManyToManyField(
                related_name="mailingsettings", to="mailing.client"
            ),
        ),
    ]
