# Generated by Django 4.2.2 on 2024-07-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingsettings",
            name="status",
            field=models.CharField(
                choices=[
                    ("Завершена", "Завершена"),
                    ("Создана", "Создана"),
                    ("Запущена", "Запущена"),
                ],
                default="Создана",
                max_length=150,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="last_try_sent_datetime",
            field=models.DateTimeField(
                auto_now_add=True,
                verbose_name="дата и время последней попытки рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(
                choices=[("Успешно", "Успешно"), ("Неудача", "Неудача")],
                max_length=50,
                null=True,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="mailingsettings",
            name="first_sent_datetime",
            field=models.DateTimeField(
                help_text="Укажите дату и время первой отправки рассылки",
                verbose_name="дата и время первой отправки рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailingsettings",
            name="period",
            field=models.CharField(
                choices=[
                    ("Раз в день", "Раз в день"),
                    ("Раз в неделю", "Раз в неделю"),
                    ("Раз в месяц", "Раз в месяц"),
                ],
                help_text="Укажите периодичность: раз в день, раз в неделю, раз в месяц",
                max_length=150,
                verbose_name="периодичность",
            ),
        ),
    ]
